# Generated by Django 4.1 on 2023-12-28 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20, unique=True)),
                ('nombre_jefe', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('tipo_contrato', models.CharField(max_length=255)),
                ('fecha_suscripcion', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objeto_contractual', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obligaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.obligaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('periodo_certificado_inicio', models.DateField()),
                ('periodo_certificado_fin', models.DateField()),
                ('nombre_archivo', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.usuario'),
        ),
    ]
